import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
im = cv.imread('C:\Image_Processing_2\daisy.jpg')
mask = np.zeros(im.shape[:2], np.uint8)
rect = (50, 150, 539, 400) 
bgd_model = np.zeros((1, 65), np.float64)
fgd_model = np.zeros((1, 65), np.float64)
cv.grabCut(im, mask, rect, bgd_model, fgd_model, 5, cv.GC_INIT_WITH_RECT)
mask2 = np.where((mask == 2) | (mask == 0), 0, 1).astype('uint8')
foreground = cv.bitwise_and(im, im, mask=mask2)
background = cv.bitwise_and(im, im, mask=cv.bitwise_not(mask2))
blurred_background = cv.GaussianBlur(background, (25, 25), 0)
enhanced_image = cv.add(blurred_background, foreground)
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.imshow(cv.cvtColor(im, cv.COLOR_BGR2RGB))
plt.title('Original Image')
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(cv.cvtColor(enhanced_image, cv.COLOR_BGR2RGB))
plt.title('Enhanced Image with Blurred Background')
plt.axis('off')
plt.show()
